CREATE TABLE kitlab_products (
    product_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    product_type TEXT NOT NULL,
    name VARCHAR(300) NOT NULL,
    url TEXT NOT NULL, 
    product_image TEXT NOT NULL,
    price DOUBLE PRECISION NOT NULL
);