CREATE TABLE kitlab_setups (
    setup_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES kitlab_users(user_id),
    setup_name TEXT NOT NULL,
    setup_info TEXT NOT NULL
);
